baseURL = "http://commandodev.com/"
languageCode = "en-gb"
title = "Commando Development"

contentdir = "content"
layoutdir = "layouts"
publishDir = "public"

cleandestinationdir = true

pygmentsCodeFences = true       # This applies to Chroma too.
# Use pygmentize generated CSS file instead of inlining the code codes in the HTML.
# See https://gohugo.io/tools/syntax-highlighting/#pygments and
# https://github.com/richleland/pygments-css
pygmentsUseClasses = true       # This applies to Chroma too.
pygmentsUseClassic = false      # Needs Hugo 0.28+, default=false => Use Chroma for syntax highlighting

enableEmoji = true

googleAnalytics = "UA-134332089-1"
# [[menu.main]]
#     name = "home"
#     url = "/"
#     weight = 1
# [[menu.main]]
#     name = "blog"
#     url = "/blog/"
#     weight = 5

[params]
  name = "Commando Development"
  description  = "Elite software development"
  favicon = "cdodev.ico"
  avatar = "img/logo.png"
  phone = "+447540722690"
  email = "ben@commando.dev"
  year = "2019"
  # description = "Commando development"

  DateForm = "2006-01-02"

  showSubheader = true
  showServices = true
  showRecentWorks = true
  showDownload = true
  showClients = true

  footerEnableContact = true
  footerEnableFollowme = true
  footerEnableTextWidget = true
  footerEnableFormWidget = true


[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/cdodevelopment"
  icon = "facebook"
  footer = true
  sharethis = true
  network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/boothead"
  icon = "twitter"
  footer = true
  sharethis = true
  network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/company/14067794"
  icon = "linkedin"
  footer = true
  sharethis = true
  network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/boothead"
    icon = "github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:ben@commando.dev"
  icon = "fa-envelope"
  footer = false
  sharethis = true
