#+STARTUP: content
#+AUTHOR: Ben Ford
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t
* Home
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_FILE_NAME: _index
:END:

* Home Section
:PROPERTIES:
:EXPORT_HUGO_SECTION: home
:EXPORT_HUGO_HEADLESS: t
:END:
** Elite software development
:PROPERTIES:
:EXPORT_FILE_NAME: elite-development
:EXPORT_HUGO_HEADLESS: t
:END:
In the Royal Marines we used
to say elite performance is a state of mind. I can show you what that means for
software development.
# {{< header imgurl="/img/cdo-memorial-crop.jpg" >}}
# {{< /header >}}

** DONE Who am I?
CLOSED: [2019-02-03 Sun 19:38]
:PROPERTIES:
:EXPORT_FILE_NAME: who-am-i
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:38]
:END:
You know that feeling of spinning your wheels, that you just can't find
*traction*? I've been there. Over my decade plus career in sowftware
development, I've experienced this in many of the companies I've worked for.
This includes everything from start ups where I was the first programmer on
board, to building teams in global mega banks.

About 4 years ago my brain basically short circuited itself and banned me from
learning more tech stuff until I figured people and teams out.

I found many *answers* in the fields of cognitive physiology, behavioural
economics and in the hundreds of book I read, but I couldn't help feeling that I
was missing something fundamental - feeling different parts of the elephant
without seeing the whole picture if you will. The most surprising thing about
this process of self education was just how many of the answers were actually
reminders of my career before technology and programming.

They were things I had already learned, and in fact deeply ingrained but not
recognised when I was a *Royal Marine* in the early 2000s.

Having this moment of recognition was a breakthrough, because it showed me that
once you are able to translate something from one domain to another and keep the
essence of why it works, you have your hands on a fundamental principle. This is
nothing new. The famous swordsman Musashi knew this way back in the 1600s:

{{% blockquote title="" source="Myamoto Musashi" %}}

"The principle of strategy is having one thing, to know ten thousand things"

{{% /blockquote %}}


The disparate lessons started to merge into *principles*. As I began to apply
these principles to other parts of my life, like my *martial arts* practice, it
also became clear that I'd been looking at many parts of the same puzzle. There
was actually *ONE PRINCIPLE* at the centre of many human endeavours.

Before I make such a bold claim, let's just take a quick look at the definition
of principle

** DONE Principles
CLOSED: [2019-02-03 Sun 19:38]
:PROPERTIES:
:EXPORT_FILE_NAME: principle
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:38]
:END:

# {{% blockquote title="Principle" source="Google Dictionary" %}}
# /ˈprɪnsɪp(ə)l/
# noun
# 1. a fundamental truth or proposition that serves as the foundation for a system
#    of belief or behaviour or for a chain of reasoning. "the basic principles of
#    justice"
# 2. a general scientific theorem or law that has numerous special applications
#    across a wide field.

# synonyms:	truth, proposition, concept, idea, theory, postulate; More
# {{% /blockquote %}}

This is what I want to show you.

The single principle that's you must understand to achieve the *operational
excellence* that every business needs to *thrive* and *scale*.

The single principle that unites the 3 pillars of *PURPOSE* *PEOPLE* and *PRACTICES*

Let's have a look at each of these in turn.

<<purpose>>
** DONE Purpose and Mission
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: purpose
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

What is your company's reason for being? What's its purpose? What's the one
mission that gets your people fired up for work in the morning?

It's critical that there's a consistent, concise message, which is shared across
the whole organisation, laying out why you're here. A company's mission is the
*WHY* that gets people pulling in the same direction.

Imagine a bunch of iron filings scattered onto a plate. Their orientation is
random there's no discernable pattern. As soon as you bring a magnet within
range though, the filings line up with an invisible force and organise
themselves to point the right direction. *MISSON* is magnetism for people.

# https://thinkgrowth.org/what-elon-musk-taught-me-about-growing-a-business-c2c173f5bff3
{{% blockquote title="Aligning Vectors" source="Elon Musk" %}}

“Every person in your company is a vector. Your progress is determined by the
sum of all vectors.”

{{% /blockquote %}}

# {{< header imgurl="/img/40-cdo-afghanistan.jpg" >}}
# {{< /header >}}

<<people>>
** DONE People and Culture
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: people
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

Companies always say that "their people are their greatest asset". But how do you
ensure that's really true? How do you build a cohesive team who support and push
each other to greatness?

If mission is the direction you're headed in and why you're making your change
in the world the culture that develops is the vessel that will take you there.
Culture is *WHO* you are. The conditions and constraints you put in place define
what that culture becomes.

You don't build a culture it is *EMERGENT* based on the environment in which it
grows.
# {{< header imgurl="/img/training.jpg" >}}
# {{< /header >}}

<<practices>>
** DONE Practices and Process
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: practices
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

When you know you do something well, when you've really nailed it, is it
repeatable? Can you teach anyone to achieve the same level of *excellence* you
have reached?

*Process* can be a bit of a dirty word in software development. It conjures up
images of big A agile consultants enforcing rituals and ceremonies that
ultimately do nothing to improve performance and everything to destroy morale.
Most professional developers will have at least one horror story of working in a
place that fell for this kind of cargo culting.

That's why I prefer to think in terms of *PRACTICES*

Practices are your playbooks. In the Royal Marines we would refer to these as
*SOPs*: Standard Operating Procedures. They are constantly evolving, improving
instructions that point the way to ever increasing performance.

** DONE What people say
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: what-people-say
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:
People say Ben is great

** DONE The Process
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_HUGO_SECTION: home
:EXPORT_FILE_NAME: the-process
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:
Working with me
* Mission Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: mission
:EXPORT_HUGO_TYPE: mission
:END:
** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
My mission is to teach growing tech based companies how to achieve and maintain
*operational excellence* as they scale

** The problem
:PROPERTIES:
:EXPORT_FILE_NAME: the-problem
:END:
Starting something is hard. You sweat, struggle and persist and you're off and
running, you start to gain momentum. You build a team around you of dedicated
*commandos*. The ones who take risks, get shit done and make things happen - the
starters. The company is small, communications overhead is minimal and you're
focused on becoming sustainable and proving your viability.

But then what?
** Scaling
:PROPERTIES:
:EXPORT_FILE_NAME: scaling
:END:

Then you start to scale up. You get more revenue, or you take on some funding.
There's more to do, so you add more people. You need to lift your eyes from the
road in front and look to the horizon, so you add *structure* and start making
plans.

Suddenly you can't move as fast as you did before. Your commandos find structure
constrictive and start to leave. A hierarchy begins to form, which slows
*communications* down and introduces noise into the system. The mission becomes
blurry and people aren't sure how what they are doing contributes to the *purpose*
of this grand enterprise that you've put in motion.

** Performing
:PROPERTIES:
:EXPORT_FILE_NAME: performing
:END:

There are organisations that have figured out how to move fast, while remaining
oriented on their goals and grounded in who they are. They get the best out of
people in insanely challenging circumstances, often under ludicrous *constraints*.
They operate by consistently holding themselves to standards that are
universally understood and shared. The foundations of this ability are
*operational excellence*, which enables *continuous improvement* and evolution.

One such organisation which has been learning an honing these lessons for over
350 years is the *Royal Marines*. Way before I was a software developer I served
in the corps, in fact I [[/about/][taught myself how to code]] en route to the second Iraq
war on board a ship. When I began my second career in software development I
looked up my time in the corps as something fun and challenging that had
certainly shaped me personally, but that didn't have much bearing on my new
direction.

*I was wrong.*

The Royal Marines have evolved from a regiment of maritime foot soldiers formed
in 1664 through constant evolution to today's role as an elite, commando trained,
rapid reaction force. They have *high performance* figured out, and can teach it
with a repeatable process that's been forged in the fire of *consistent improvement*
since the time we've had armies.

When I started to realise just what fundamental lessons I'd been exposed to in
the corps I spent all my spare time working out how to distil those lessons down
to the *fundamental principles* which could be used in any domain. While the
principles are universal - the implementation of teaching them in the corps
involves lots of cold water and certainly wouldn't suit everyone.

** Why I'm here
:PROPERTIES:
:EXPORT_FILE_NAME: why-im-here
:END:

So that's why I'm here.

I want to show you how to apply the foundational principles that underpin elite
performance to your tech business so that you can make your difference in the world.

* About Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: about
:EXPORT_HUGO_TYPE: about
:END:
** About
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
I learned to code on a warship in 2003 on the way to Iraq. I've been a commando,
a bouncer, a barman, a refuse collector (for one day), an itinerant marquee
fabricator, a telecoms engineer and a programmer.

** My Story
:PROPERTIES:
:EXPORT_FILE_NAME: my-story
:END:
My father is an engineer and we spent much of my early childhood in Africa
(Malawi and Lesotho) and the Caribbean (Jamaica).

Having grown up in so many different cultures meant that moving back to the UK
and fitting into a homogeneous environment was a bit of a challenge and
strengthened my naturally *introspective* nature. Being somewhat isolated during
my school years did however strengthen my intense *curiosity*. It also served to
direct that curiosity away from just figuring out physical objects (I loved to
pull things apart and put them back together) and towards trying to figure out
people. This obsession has lasted ever since.

Like many people of my generation, *bullying* was a feature of growing up. I'm
sure that was a major driver that lead me at about 13 or 14 to decide that I
would one day join the Royal Marine Commandos. This to my young eyes epitomised
toughness and fitting in to a close nit social structure that had eluded me at
school.
** The Royal Marines
:PROPERTIES:
:EXPORT_FILE_NAME: the-rm
:END:

Having decided on the Royal Marines in my teens, I didn't actually end up
joining until I was just shy of my 23rd birthday. This put me towards the older
end of the intake (although thankfully not as old as "grandad" the ancient 25
year old).

*Commando training* was a monumental challenge, as it's designed to be. I remain
incredibly proud of earning my *green beret*, but it was really the lessons I
learned about communicating with people (mainly taught through the medium of
doing it incredibly poorly) that I feel were the most important benefit from
that extremely intense period of my life.

During my 4 years in the corps I completed operational tours of *Sierra Leone*
shortly after the brutal civil war, the bandit country of *South Armagh* in the
closing years of the troubles in Northern Ireland, and finally *Op Telic 1: the
second gulf war* in 2003.

The Royal Marines is a special kind of unit with its own ethos, but ultimately,
like almost all military units, it's a very rigid and hierarchical. You either
fit into that *structure* or you don't. I decided that I wasn't going to make it a
career until I had a pension, and I was also sceptical that the way the war
against terror was escalating was the right course so in about 2003 I began
thinking about what would come next.

** Teaching myself programming
:PROPERTIES:
:EXPORT_FILE_NAME: teaching-myself
:END:

In 2003 the unit I was part of, Commando Helicopter Force, was tasked with
supporting the invasion of *Iraq*. We were embarked aboard HMS Ocean, and in early
2003 we set sail from Plymouth, bound for the middle east.

There was a lot of time on board ship and I had a shiny new laptop with me that
a friend had convinced me to put *Linux* on. In the process of installing Red Hat
(and bricking the laptop) I had come across the seminal [[http://www.catb.org/esr/faqs/hacker-howto.html][How to Become a Hacker]]
faq by Eric S Raymond, so after we got underway I begged some internet access in
the ships communications centre and bought a book on *python* from amazon. Over
the next few weeks in my down time below desks, with no internet access I banged
my head against it until I had roughly figured out how to write a computer
program.

** Progression
:PROPERTIES:
:EXPORT_FILE_NAME: progression
:END:

I left the Royal Marines in 2004 and went into *telecoms* operations. The
difference in technology in a modern 3G network compared to what I was working
with in the corps (40 year old analog tech) was stark, and I was also able to
work parts of my embryonic programming skills into my roles. A script to ping
hosts here, a reporting tool there. Finally I was up to the point of making
django web apps by about 2006 which took me to Indonesia and my first foray into
*entrepreneurship*. I also met the *love of my life* and got married!

In 2008 we moved back to the UK and I moved into a career as a full time
programmer. At this point in my life I mostly looked at my time in the Royal
Marines as something that was a great *challenge* and great fun, but as something
separate from my new career.

*I was so wrong.*

** Full circle
:PROPERTIES:
:EXPORT_FILE_NAME: full-circle
:END:

Fast forward a few years, having gone through a few programming languages to
settle on *Haskell* and a few jobs in finance and start ups and I started to
realise that the experiences I was exposed to in the Royal Marines were
absolutely foundational to understanding performance and how people work
together. I have always been an avid reader and as my technical skills matured I
started to refocus on my fascination with *leadership* and people. Eventually I
read and experienced enough to start making connections between different
fields. I began to see commonalities across learning and leadership in the
forces and technical projects. I began to see how lessons from my martial arts
practice apply to learning a new programming language or operational skill.

There's a concept from Japanese zen which captures this process perfectly.
*Ensō* symbolises enlightenment and the void, which I think is fitting. Often
when you have an intellectual or spiritual breakthrough you realise that you
haven't got somewhere new, but that you have returned to the beginning with a
mindset for new understanding

* Blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
** Blog
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

# :EXPORT_HUGO_MENU: :menu "main"
My Blog

** Ethos
:PROPERTIES:
:EXPORT_FILE_NAME: ethos
:EXPORT_HUGO_MENU: :parent blog
:END:
First blog post about ethos and stuff

** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: mission
:EXPORT_HUGO_MENU: :parent blog
:END:
Mission really is everyt
** TODO Intuition vs Cognition                                           :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: intuition-vs-cognition
:EXPORT_HUGO_MENU: :parent blog
:END:
[[https://www.kotterinc.com/research-and-perspectives/survive-thrive/][Survive + Thrive - Kotter]]
* Brief
:PROPERTIES:
:EXPORT_HUGO_SECTION: brief
:END:

** Brief
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

*** General info

This year I am launching a new business that leverages my unique background as
both a Royal Marine and someone operating at a high level of technical skill as
a developer, technologist and leader. For several years I've been an IT contractor. Over
the course of this year, I want to transition into doing more leveraged training
and coaching work.

The way I envisage this working - which has not yet been tested by first contact
with the enemy :-) is that I will sell a mixture of premium digital products and
high ticket consulting with clients. The digital products will start with a
course on instilling operational excellence within a development team. It will
be aimed at either the business owner or the technical team lead. Further
courses may well follow such as:

- Becoming a better developer
- How to work within a team
- How to structure training

The coaching side of the business is envisaged as a leveraged delivery model (so
many clients at once) offering an operational transformation over approximately
a 90 day period. It will more than likely be based on the structure of the
initial course that I plan to start selling in the next month or so. So: 6 ish
sections (TBC) each with a theory and practice element to them. Delivery will
hopefully be remote with the theory and practice being delivered at the
beginning of the week and some form of implementation and follow up offered
before the next module in about 2 weeks time.

** Who Am I?
:PROPERTIES:
:EXPORT_FILE_NAME: me
:EXPORT_HUGO_WEIGHT: 10
:END:

Brand and values

<!--more-->

*** What do I do?

I have a unique background (pretty much). I don't know of anyone else who's had
elite military experience and then gone on to have a career is technology and
programming (at least on the implementation side). I've also had a life long
interest in studying psychology and high performance. I want to apply these 3
aspects to helping tech companies build the best teams possible.

{{% blockquote title="Positioning Statement" %}}

 I help early stage tech companies navigate the phase shift from start up to
 established company. Having built and led teams in all sizes of company and
 leaning on experience of elite military operations from my time in the Royal
 Marine Commandos I will show you how to implement standards without stifling
 your essence. Operational excellence is the fuel you must have to propel you to
 the next level, I can help get you there.
{{% /blockquote %}}

*** How do I do it?
I will offer a transformation based around the core principle of helping
understand their feedback loops at all levels of the company and how to optimise
them. At the end of my engagement companies will have effective development
teams that are aligned with the mission and purpose of the company and
operationally set up for repeatable high performance. They will have an
operating manual which serves many purposes:

- A living record of the way things are done
- A set of instructions for existing staff
- An onboarding aim for new hires
- A record of the company's culture and values
*** What's my point of difference
I have several major points of difference:

**** Military background
This gives me a very unusual perspective compared to the vast majority of people
in tech.
**** Self taught
I am self directed and motivated (and learning to code on a warship is a cool story)
**** Leadership and team building experience
I've walked the walk both at start ups and established companies.
**** Broad background knowledge and intuition
I've read probably 500 or so books on leadership/development/military theory, and
I've made links between all of these to come up with a simple focus on
principles which I think is pretty unique
*** Who am I doing this for?
In the first instance I'm doing this for my customers. But I have an eye on
being able to give back and pay it forward for lads that come after me, or those
that haven't been as lucky as me.
**** Ideal customers
My ideal customer is a growing software or technology company which is
navigating the inevitable social inflection points that a growing team hits.

I'm looking for companies that are at the 30 ish or 100-150 ish people phase
shifts. It's at these point where there is a shift to more or different process
and I want to position myself to mentor the company or tech leadership to
successfully navigate this change.

The company should have a clear mission and purpose (or at least stand a chance
of defining that) and should want to be in the cutting edge of innovation and
learning. They are most probably a start up growing into an established company
but experiencing some growing pains getting there.

Operational Excellence should put the company in the exceptional quadrant on all
the metrics that matter from Accelerate (a book about devops with a very
quantitative approach) and will ensure that they can out manoeuvre their
competition and the market incumbents.

The engagement will most likely look like an intensive period of transformation
during which the implementation plan is formulated and I ensure that the company
has the tools and aptitude to succeed. Once they have that I will scale down to
an advisory and mentoring role and look at a retainer going forward.

Outcomes for the company will be a more agile, able team that is fully aligned
with the missing and able to execute efficiently to give the company the
greatest possible chance of shaping and adapting to unfolding circumstances and
surviving on their own terms.
**** People leaving the forces
When people (especially enlisted) leave the forces they still aren't getting
good information. I would like to be able to take any success I have from this
venture and help show people leaving the forces just how fundamental the skills
and experiences they have had are.

**** Military Charities
I also want to be successful enough that I can comfortably give some percentage
of my time and earnings to charities/causes who are helping those that haven't
had it so easy. For example Rock2Recovery and others doing great work.
*** Values
Courage, Determination, Unselfishness, Cheerfulness in the face of adversity,
Humility, Excellence, Integrity. All of these are relevant from our time in the
corps. Some other values I've picked up along the way:

*Elegance* - spend a bit more effort to find a solution that is unforced and
natural.

*Structure* - find the right amount to be supportive, not stifling.

*Fundamental* - keep deconstructing until you have reached something
irreducible.

*Kaizen* - always be learning and improving.

*Detachment* - take the world as it is, not as you wish it was.

*** Personality
The personality of Commando Development should in many ways reflect that of the
corps.

*Confidence* tempered with humility: We know what we can do, but we know how much
more there is to learn.

*Precicision* We strive for clarity and succinctness.

*Sharp* and focused

*Wry sense of humor* We don't take ourselves too seriously

*Unflappable* We deal with whatever comes our way calmly


** Logistics
:PROPERTIES:
:EXPORT_FILE_NAME: logistics
:EXPORT_HUGO_WEIGHT: 20
:END:

General commercial info and planning info

<!--more-->

*** Company details
Commando Development Ltd
https://commandodev.com

(contacts on the website)

I also own:

- commandodevelopment.com
- commandodev.co.uk
- cdodev.co.uk
- commandodeveloper.com
- commandodevelopers.com

*** Intended launch date
Web site is already live. I'd like to get a more on brand presence out there be
within 30 days as that's the time frame that I want to work to for beginning to
get customers
*** Budget
Limited - I want something constrained enough that I'm not totally embarrased,
but that's enough for me to start selling. After I get revenue, I'm very
prepared to plow some of that back into improving the brand and message
*** Current website
The current website is something that I've put together as a mean to start
gathering content. I like the minimalist feel, but I want to develop a proper
band voice.

It's using the unify theme and built using bootstrap:
https://htmlstream.com/preview/unify-v2.6/index.html. There are various elements
available like paralax images, video carosels etc.

At the moment there has been no marketing and the site, although live, is
essentually hidden.

*** Purpose of new website
The new website is intended to be where I hand my shingle out and as a primary
marketing source. It will more than likely be where I send customers to specific
landing pages and well as to capture details for marketing purposes. Over time I
will integrate things like:

- Email address gathering (convertkit)
- Segmentation and A/B testing (right message)
- Consulting call booking (calendly)
- Custom built functionality
- SaaS apps if and when appropriate

**** Audience
The primary audience (at least at first) will be cold and warm leads who come in
through paid advertising channels. I will almost certainly want to segment them
into separate audiences. The two big divisions I forsee to start with are
technical leaders or business owners vs individual contributors or more junior
folks.

They will have a technical background and will most likely be the kinds of
people that will notice any less well executed elements. For this reason the
site will be static (for speed) served over https, and must look extremely
technically competent.

People will be sent to the site for the primary reason of growing my audience
initially - I doubt I'll be selling directly from the site to start with.
**** Perception
I'm trying to bring the ethos that we know from the corps to software
development. So:

excellence, precision, persistence, elite, pragmatic, good enough vs perfect,
continuous improvement, curiosity, performance, process, shared standards,
courage to do the right thing,

*** Competitors/similar companies
I don't really have any direct competitors I don't think. There are people like
agile, change and leadership consultants like the following. But I don't know of
any one in particular doing operational excellence specifically

**** Dan North
https://dannorth.net/

**** Accomplish (ex bootnecks as well)
I like the clean look these guys have
http://www.accomplish.world/

**** Albany
https://www.albanyassociates.com/
**** Leadership Forces
Rod is an ex bootneck and someone I may well partner with in future
http://www.leadershipforces.com/

**** DRM group
David is an ex bootneck selling resilience mainly to larger companies
https://www.drmgroup.co.uk/
**** EQ Commando
Shaun is an ex bootneck, now doing emotional intelligence coaching
https://www.eq2lead.uk/the-eq-commando
*** Inspiration
**** Jame Clear
I like the clean look and the content organisation
https://jamesclear.com/
**** Double your freelancing
Brennan is a master at marketing and systemising
https://doubleyourfreelancing.com/
**** Stacking the bricks
Amy Hoy is also a master at selling digital products and courses
https://stackingthebricks.com/
**** Cal Newport
Cal is a minimalist and productivity expert
http://calnewport.com
**** Rob Stewart
Ex RAF pilot. Teaches coaches marketing and systems
http://www.robstewartglobal.com/

** Content
:PROPERTIES:
:EXPORT_FILE_NAME: content
:EXPORT_HUGO_WEIGHT: 30
:END:

Types of content and elements

<!--more-->

** Technology
:PROPERTIES:
:EXPORT_FILE_NAME: tech
:EXPORT_HUGO_WEIGHT: 40
:END:

Implementation plan and technology

<!--more-->
* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# eval: (auto-fill-mode 1)
# End:
