#+STARTUP: content
#+AUTHOR: Ben Ford
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t
* Home
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_MENU: :menu "main"
:END:

** A heading I guess
My super home page

* Mission Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: mission
:EXPORT_HUGO_TYPE: mission
:END:
** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
My mission is to teach growing tech based companies how to achieve and maintain
operational excellence as they scale

** Another mission section
:PROPERTIES:
:EXPORT_FILE_NAME: mission-sec-1
:END:
Mission section
* About Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: about
:EXPORT_HUGO_TYPE: about
:END:
** About
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
I learned to code on a warship in 2003 on the way to Iraq. I've been a commando,
a bouncer, a barman, a refuse collector (for one day), an itinerant marquee
fabricator, a telecoms engineer and a programmer.

Throughout all those experiences, I've also always remained a dedicated student
of the human condition. How we interact with and process the experiences we have
completely fascinates me.

** My Story
:PROPERTIES:
:EXPORT_FILE_NAME: my-story
:END:
My father is an engineer and we spent much of my early childhood in Africa
(Malawi and Lesotho) and the Caribbean (Jamaica). While these experiences were
undoubtedly foundational in shaping the person I've become, to 9 year old me
moving back to a small Essex town with a broad Jamaican accent, this didn't
really seem to be the case.

Having grown up in so many different cultures meant that fitting back into a
homogeneous environment was a bit of a challenge and strengthened my naturally
introspective nature. Being somewhat isolated during my school years did however
strengthen my intense curiosity. It also served to direct that curiosity away
from just figuring out physical objects (I loved to pull things apart and put
them back together) and towards trying to figure out people. This obsession has
lasted ever since.

Like many people of my generation, bullying was a feature of growing up. I'm
sure that was a major driver that lead me at about 13 or 14 to decide that I
would one day join the Royal Marine Commandos. This to my young eyes epitomised
toughness and fitting in to a close nit social structure that had eluded me at
school.
** The Royal Marines
:PROPERTIES:
:EXPORT_FILE_NAME: the-rm
:END:

Having decided on the Royal Marines in my teens, I didn't actually end up
joining until I was just shy of my 23rd birthday. This put me towards the older
end of the intake (although thankfully not as old as "grandad" the ancient 25
year old).

Commando training was a monumental challenge, as it's designed to be. I remain
incredibly proud of earning my green beret, but it was really the lessons I
learned about communicating with people (mainly taught through the medium of
doing it incredibly poorly) that I feel were the most important benefit from
that extremely intense period of my life.

During my 4 years in the corps I completed operational tours of Sierra Leone
shortly after the brutal civil war, the bandit country of South Armagh in the
closing years of the troubles in Northern Ireland, and finally Op Telic 1: the
second gulf war in 2003.

The Royal Marines is a special kind of unit with its own ethos, but ultimately,
like almost all military units, it's a very rigid and hierarchical. You either
fit into that structure or you don't. I decided that I wasn't going to make it a
career until I had a pension, and I was also sceptical that the way the war
against terror was escalating was the right course so in about 2003 I began
thinking about what would come next.

** Teaching myself programming
:PROPERTIES:
:EXPORT_FILE_NAME: teaching-myself
:END:

In 2003 the unit I was part of, Commando Helicopter Force, was tasked with
supporting the invasion of Iraq. We were embarked aboard HMS Ocean, and in early
2003 we set sail from Plymouth, bound for the middle east.

There was a lot of time on board ship and I had a shiny new laptop with me that
a friend had convinced me to put Linux on. In the process of installing Red Hat
(and bricking the laptop) I had come across the seminal [[http://www.catb.org/esr/faqs/hacker-howto.html][How to Become a Hacker]]
faq by Eric S Raymond, so after we got underway I begged some internet access in
the ships communications centre and bought a book on python from amazon. Over
the next few weeks in my down time below desks, with no internet access I banged
my head against it until I had roughly figured out how to write a computer
program.

* Blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
** Blog
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_MENU: :menu "main"
:END:

My Blog

** Ethos
:PROPERTIES:
:EXPORT_FILE_NAME: ethos
:EXPORT_HUGO_MENU: :parent blog
:END:
First blog post about ethos and stuff

** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: mission
:EXPORT_HUGO_MENU: :parent blog
:END:
Mission really is everyt
* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# eval: (auto-fill-mode 1)
# End:
