#+STARTUP: content
#+AUTHOR: Ben Ford
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t
* Home
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_FILE_NAME: _index
:END:

* Home Section
:PROPERTIES:
:EXPORT_HUGO_SECTION: home
:EXPORT_HUGO_HEADLESS: t
:END:
** Elite software development
:PROPERTIES:
:EXPORT_FILE_NAME: elite-development
:EXPORT_HUGO_HEADLESS: t
:END:
In the Royal Marines we used
to say elite performance is a state of mind. I can show you what that means for
software development.
# {{< header imgurl="/img/cdo-memorial-crop.jpg" >}}
# {{< /header >}}

** DONE Who am I?
CLOSED: [2019-02-03 Sun 19:38]
:PROPERTIES:
:EXPORT_FILE_NAME: who-am-i
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:38]
:END:
You know that feeling of spinning your wheels, that you just can't find
*traction*? I've been there, in companies large and small, as a programmer and a
technical leader. About 4 years ago my brain basically short circuited itself
and banned me from learning more tech stuff until I figured people out. I found
*answers*, lots of them. The most surprising thing about this process of self
education was just how many of the answers were actually reminders.

They were things I had already learned when I was a *Royal Marine* in the early 2000s.

I dug more, read more, and the many answers I thought I had found started to
coalesce. The disparate lessons started to merge into *principles*. As I began
to apply these principles to other parts of my life, like my *martial arts*
practice, it also became clear that I'd been looking at many parts of the same
puzzle. There was actually *ONE PRINCIPLE* at the centre of many human
endeavours.

Before I make such a bold claim, let's just take a quick look at the definition
of principle

** DONE Principles
CLOSED: [2019-02-03 Sun 19:38]
:PROPERTIES:
:EXPORT_FILE_NAME: principle
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:38]
:END:

# {{% blockquote title="Principle" source="Google Dictionary" %}}
# /ˈprɪnsɪp(ə)l/
# noun
# 1. a fundamental truth or proposition that serves as the foundation for a system
#    of belief or behaviour or for a chain of reasoning. "the basic principles of
#    justice"
# 2. a general scientific theorem or law that has numerous special applications
#    across a wide field.

# synonyms:	truth, proposition, concept, idea, theory, postulate; More
# {{% /blockquote %}}

This is what I want to show you.

The single principle that's you must understand to achieve the *operational
excellence* that every business needs to *thrive* and *scale*.

The single principle that unites the 3 pillars of

[[purpose][*PURPOSE*]]

[[purpose][*PEOPLE*]]

*PRACTICES*

<<purpose>>
** DONE Purpose and Mission
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: purpose
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

What is your company's reason for being? What's its purpose? What's the one
HA that gets your people fired up for work in the morning?
# {{< header imgurl="/img/40-cdo-afghanistan.jpg" >}}
# {{< /header >}}

<<people>>
** DONE People and Culture
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: people
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

Companies always say that "their people are their greatest asset". But how do you
ensure that's really true? How do you build a cohesive team who support and push
each other to greatness?
# {{< header imgurl="/img/training.jpg" >}}
# {{< /header >}}

<<pract>>
** DONE Practices and Process
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: practices
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:

When you know you do something well, when you've really nailed it, is it
repeatable? Can you teach anyone to achieve the same level of excellence you
have reached?

** DONE What people say
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_FILE_NAME: what-people-say
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:
People say Ben is great

** DONE The Process
CLOSED: [2019-02-03 Sun 19:36]
:PROPERTIES:
:EXPORT_HUGO_SECTION: home
:EXPORT_FILE_NAME: the-process
:EXPORT_HUGO_HEADLESS: t
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-02-03 Sun 19:36]
:END:
Working with me
* Mission Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: mission
:EXPORT_HUGO_TYPE: mission
:END:
** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
My mission is to teach growing tech based companies how to achieve and maintain
*operational excellence* as they scale

** The problem
:PROPERTIES:
:EXPORT_FILE_NAME: the-problem
:END:
Starting something is hard. You sweat, struggle and persist and you're off and
running, you start to gain momentum. You build a team around you of dedicated
*commandos* - the ones who take risks, get shit done and make things happen - the
starters. The company is small, communications overhead is minimal and you're
focused on becoming sustainable and proving your viability.

But then what?
** Scaling
:PROPERTIES:
:EXPORT_FILE_NAME: scaling
:END:

Then you start to scale up. You get more revenue, or you take on some funding.
There's more to do, so you add more people. You need to lift your eyes from the
road in front and look to the horizon, so you add *structure* and start making
plans.

Suddenly you can't move as fast as you did before. Your commandos find structure
constrictive and start to leave. A hierarchy begins to form, which slows
*communications* down and introduces noise into the system. The mission becomes
blurry and people aren't sure how what they are doing contributes to the *purpose*
of this grand enterprise that you've put in motion.

** Performing
:PROPERTIES:
:EXPORT_FILE_NAME: performing
:END:

There are organisations that have figured out how to move fast, while remaining
oriented on their goals and grounded in who they are. They get the best out of
people in insanely challenging circumstances, often under ludicrous *constraints*.
They operate by consistently holding themselves to standards that are
universally understood and shared. The foundations of this ability are
*operational excellence*, which enables *continuous improvement* and evolution.

One such organisation which has been learning an honing these lessons for over
350 years is the *Royal Marines*. Way before I was a software developer I served
in the corps, in fact I [[/about/][taught myself how to code]] en route to the second Iraq
war on board a ship. When I began my second career in software development I
looked up my time in the corps as something fun and challenging that had
certainly shaped me personally, but that didn't have much bearing on my new
direction.

*I was wrong.*

The Royal Marines have evolved from a regiment of maritime foot soldiers formed
in 1664 through constant evolution to today's role as an elite, commando trained,
rapid reaction force. They have *high performance* figured out, and can teach it
with a repeatable process that's been forged in the fire of *consistent improvement*
since the time we've had armies.

When I started to realise just what fundamental lessons I'd been exposed to in
the corps I spent all my spare time working out how to distil those lessons down
to the *fundamental principles* which could be used in any domain. While the
principles are universal - the implementation of teaching them in the corps
involves lots of cold water and certainly wouldn't suit everyone.

** Why I'm here
:PROPERTIES:
:EXPORT_FILE_NAME: why-im-here
:END:

So that's why I'm here.

I want to show you how to apply the foundational principles that underpin elite
performance to your tech business so that you can make your difference in the world.

* About Section
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_BUNDLE: about
:EXPORT_HUGO_TYPE: about
:END:
** About
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_MENU: :menu "main"
:END:
I learned to code on a warship in 2003 on the way to Iraq. I've been a commando,
a bouncer, a barman, a refuse collector (for one day), an itinerant marquee
fabricator, a telecoms engineer and a programmer.

** My Story
:PROPERTIES:
:EXPORT_FILE_NAME: my-story
:END:
My father is an engineer and we spent much of my early childhood in Africa
(Malawi and Lesotho) and the Caribbean (Jamaica).

Having grown up in so many different cultures meant that moving back to the UK
and fitting into a homogeneous environment was a bit of a challenge and
strengthened my naturally *introspective* nature. Being somewhat isolated during
my school years did however strengthen my intense *curiosity*. It also served to
direct that curiosity away from just figuring out physical objects (I loved to
pull things apart and put them back together) and towards trying to figure out
people. This obsession has lasted ever since.

Like many people of my generation, *bullying* was a feature of growing up. I'm
sure that was a major driver that lead me at about 13 or 14 to decide that I
would one day join the Royal Marine Commandos. This to my young eyes epitomised
toughness and fitting in to a close nit social structure that had eluded me at
school.
** The Royal Marines
:PROPERTIES:
:EXPORT_FILE_NAME: the-rm
:END:

Having decided on the Royal Marines in my teens, I didn't actually end up
joining until I was just shy of my 23rd birthday. This put me towards the older
end of the intake (although thankfully not as old as "grandad" the ancient 25
year old).

*Commando training* was a monumental challenge, as it's designed to be. I remain
incredibly proud of earning my *green beret*, but it was really the lessons I
learned about communicating with people (mainly taught through the medium of
doing it incredibly poorly) that I feel were the most important benefit from
that extremely intense period of my life.

During my 4 years in the corps I completed operational tours of *Sierra Leone*
shortly after the brutal civil war, the bandit country of *South Armagh* in the
closing years of the troubles in Northern Ireland, and finally *Op Telic 1: the
second gulf war* in 2003.

The Royal Marines is a special kind of unit with its own ethos, but ultimately,
like almost all military units, it's a very rigid and hierarchical. You either
fit into that *structure* or you don't. I decided that I wasn't going to make it a
career until I had a pension, and I was also sceptical that the way the war
against terror was escalating was the right course so in about 2003 I began
thinking about what would come next.

** Teaching myself programming
:PROPERTIES:
:EXPORT_FILE_NAME: teaching-myself
:END:

In 2003 the unit I was part of, Commando Helicopter Force, was tasked with
supporting the invasion of *Iraq*. We were embarked aboard HMS Ocean, and in early
2003 we set sail from Plymouth, bound for the middle east.

There was a lot of time on board ship and I had a shiny new laptop with me that
a friend had convinced me to put *Linux* on. In the process of installing Red Hat
(and bricking the laptop) I had come across the seminal [[http://www.catb.org/esr/faqs/hacker-howto.html][How to Become a Hacker]]
faq by Eric S Raymond, so after we got underway I begged some internet access in
the ships communications centre and bought a book on *python* from amazon. Over
the next few weeks in my down time below desks, with no internet access I banged
my head against it until I had roughly figured out how to write a computer
program.

** Progression
:PROPERTIES:
:EXPORT_FILE_NAME: progression
:END:

I left the Royal Marines in 2004 and went into *telecoms* operations. The
difference in technology in a modern 3G network compared to what I was working
with in the corps (40 year old analog tech) was stark, and I was also able to
work parts of my embryonic programming skills into my roles. A script to ping
hosts here, a reporting tool there. Finally I was up to the point of making
django web apps by about 2006 which took me to Indonesia and my first foray into
*entrepreneurship*. I also met the *love of my life* and got married!

In 2008 we moved back to the UK and I moved into a career as a full time
programmer. At this point in my life I mostly looked at my time in the Royal
Marines as something that was a great *challenge* and great fun, but as something
separate from my new career.

*I was so wrong.*

** Full circle
:PROPERTIES:
:EXPORT_FILE_NAME: full-circle
:END:

Fast forward a few years, having gone through a few programming languages to
settle on *Haskell* and a few jobs in finance and start ups and I started to
realise that the experiences I was exposed to in the Royal Marines were
absolutely foundational to understanding performance and how people work
together. I have always been an avid reader and as my technical skills matured I
started to refocus on my fascination with *leadership* and people. Eventually I
read and experienced enough to start making connections between different
fields. I began to see commonalities across learning and leadership in the
forces and technical projects. I began to see how lessons from my martial arts
practice apply to learning a new programming language or operational skill.

There's a concept from Japanese zen which captures this process perfectly.
*Ensō* symbolises enlightenment and the void, which I think is fitting. Often
when you have an intellectual or spiritual breakthrough you realise that you
haven't got somewhere new, but that you have returned to the beginning with a
mindset for new understanding

* Blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
** Blog
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_MENU: :menu "main"
:END:

My Blog

** Ethos
:PROPERTIES:
:EXPORT_FILE_NAME: ethos
:EXPORT_HUGO_MENU: :parent blog
:END:
First blog post about ethos and stuff

** Mission
:PROPERTIES:
:EXPORT_FILE_NAME: mission
:EXPORT_HUGO_MENU: :parent blog
:END:
Mission really is everyt
* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# eval: (auto-fill-mode 1)
# End:
